// app/scripts/currency.download.vue
<docs>
Currency download page, implemented in vue.js.
</docs>

<template>
    <div>
        <h3>Book currencies</h3>
        <CurrencyTable v-bind:currencies="currencies" />
        <div className="text-center">
            <button class="btn btn-primary" @click="downloadAll">
                Download all
            </button>
            <button v-if="importEnabled" class="btn btn-outline-primary ml-3" @click="importAll">
                Import all
            </button>
        </div>
    </div>
</template>
<script>
import CurrencyTable from "./currency.download.table.vue";

/**
 * Represents the data model for the currency row.
 */
class Currency {
  constructor() {
    //super();
    this.symbol = undefined;
    this.rate = undefined;
    this.rateDate = undefined;
    this.saved = false;
  }
}

export default {
  data() {
    return {
      currencies: [],
      // Response from the server when getting the rates from rates provider.
      response: null,
      importEnabled: false
    };
  },
  //   props: ['currencies'],
  methods: {
    /**
     * Stores and displays the information received from the rates server.
     */
    displayRates: function(rates_result) {
      // Populate rows by updating the collection.
      this.response = rates_result;
      var rates_dict = rates_result.rates;

      for (var i = 0; i < this.currencies.length; i++) {
        var cur = this.currencies[i];
        var rate = rates_dict[cur.symbol];
        // console.log("assigning", rate, "to", cur.symbol);
        cur.rate = rate;
        cur.rateDate = rates_result.date;
      }
    },

    downloadAll: function(event) {
      // Just get all and then parse the result
      // console.log("fetching rates...");
      var that = this;
      $.ajax({
        url: "https://api.fixer.io/latest",
        method: "GET",
        success: function(data) {
          // console.log("received:", data);
          that.displayRates(data);
          that.enableImport();
        }
      });
    },

    enableImport: function() {
      this.importEnabled = true;
    },

    get_book_currencies: function() {
      var that = this;

      $.ajax({
        url: "/currency/api/book_currencies",
        success: function(data) {
          that.initCurrencies(data);
        }
      });
    },

    importAll: function() {
      // Send the rates to GnuCash Portfolio.

      // clear the output first.
      this.setSaved(false);

      var that = this;
      $.ajax({
        url: "/currency/api/saverates",
        method: "POST",
        data: {
          currencies: JSON.stringify(this.currencies),
          base: this.response.base,
          date: this.response.date
        },
        success: function(data) {
          var saved = false;
          if (data == "true") {
            saved = true;
          }

          // Display result
          that.setSaved(saved);
        }
      });
    },

    /**
     * Initialize the list of Currency objects from the list of symbols received from the page.
     */
    initCurrencies: function(symbolsString) {
      var symbols = JSON.parse(symbolsString);
      // console.log("got", symbols);

      var currencies = [];
      // console.log("received", symbols.length, "symbols.");

      for (var i = 0; i < symbols.length; i++) {
        var symbol = symbols[i];
        // console.log("creating", symbol);
        var currency = new Currency();
        currency.symbol = symbol;

        currencies.push(currency);
      }

      // console.log(currencies);
      // return currencies;
      this.currencies = currencies;
    },

    setSaved: function(value) {
      // Set all currency 'saved' indicators to the given value.

      for (var i = 0; i < this.currencies.length; i++) {
        this.currencies[i].saved = value;
      }
    }
  },
  mounted: function() {
    // `this` points to the vm instance
    // console.log('a is: ' + this.a)
    console.log("Initializing currencies...");
    this.get_book_currencies();
  },
  components: {
    CurrencyTable
  }
};
</script>

// app/scripts/currency.download.jsx
/*
    Currency exchange rate download mini-app.
*/

/**
 * Represents the data model for the currency row.
 */
class Currency {
    constructor() {
        //super();
        this.symbol = undefined;
        this.rate = undefined;
        this.rateDate = undefined;
        this.saved = false;
    }
}

class CurrencyTableRow extends React.Component {
    constructor(prop) {
        super(prop);
        this.state = {
            currency: prop.currency
        };
    }
    render() {
        let indicator = false;
        if (this.state.currency.saved) {
            indicator = <span>True</span>;
        }

        return (

            <tr key={this.state.currency.symbol}>
                <td>
                    {this.state.currency.symbol}
                </td>
                <td>{this.state.currency.rate}</td>
                <td>
                    {this.state.currency.rateDate}
                </td>
                <td>
                    {indicator}
                </td>
            </tr>

        );
    }
}

/**
 * Currency rate table. 
 * Displays the book currencies and the downloaded rates.
 */
class CurrencyTable extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            currencies: props.currencies
        };
    }

    render() {
        return (
            <table className="table table-bordered table-striped">
                <thead className="thead-dark">
                    <tr>
                        <th>Currency</th>
                        <th>Value</th>
                        <th>Date</th>
                        <th>Saved</th>
                    </tr>
                </thead>
                <tbody>
                    {this.state.currencies.map((currency, i) =>
                        <CurrencyTableRow key={currency.symbol} currency={currency} />
                    )}
                </tbody>
            </table>
        )
    }
}

class Main extends React.Component {
    constructor(props) {
        super(props);

        var currencies = this.initCurrencies(props.currencies);
        this.state = {
            currencies: currencies,
            importEnabled: false,
            response: undefined     // response from the rates server.
        };
    }

    /**
     * Initialize the list of Currency objects from the list of symbols received from the page.
     */
    initCurrencies = function (symbols) {
        var currencies = [];
        // console.log("received", symbols.length, "symbols.");

        for (var i = 0; i < symbols.length; i++) {
            var symbol = symbols[i];
            // console.log("creating", symbol);
            var currency = new Currency();
            currency.symbol = symbol;

            currencies.push(currency);
        }

        // console.log(currencies);
        return currencies;
    }

    downloadAll = function (event) {
        // Just get all and then parse the result
        // console.log("fetching rates...");
        var that = this;
        $.ajax({
            url: 'https://api.fixer.io/latest',
            method: 'GET',
            success: function (data) {
                // console.log("received:", data);
                that.displayRates(data);
                that.enableImport();
            }
        });
    };

    enableImport = function () {
        this.setState({ importEnabled: true });
    }

    /**
     * Stores and displays the information received from the rates server.
     */
    displayRates = function (rates_result) {
        // Populate rows by updating the collection.
        var rates_dict = rates_result.rates;
        var currencies = this.state.currencies;

        for (var i = 0; i < currencies.length; i++) {
            var cur = currencies[i];
            var rate = rates_dict[cur.symbol];
            // console.log("assigning", rate, "to", cur.symbol);
            cur.rate = rate;
            cur.rateDate = rates_result.date;
        }
        this.setState({
            currencies: currencies,
            response: rates_result
        });
    }

    setSaved = function (value) {
        var currencies = this.state.currencies;

        for (var i = 0; i < currencies.length; i++) {
            currencies[i].saved = value;
        }

        this.setState({ currencies: currencies });
    }

    importAll = function () {
        // Send the rates to GnuCash Portfolio.

        // clear the output first.
        this.setSaved(false);

        var that = this;
        $.ajax({
            url: '/currency/api/saverates',
            method: 'POST',
            data: {
                currencies: JSON.stringify(this.state.currencies),
                base: this.state.response.base,
                date: this.state.response.date
            },
            success: function (data) {
                var saved = false;
                if (data == "true") {
                    saved = true;
                }

                // Display result
                that.setSaved(saved);
            }
        });
    }

    render() {
        return (
            <div>
                <h3>Book currencies</h3>
                <CurrencyTable currencies={this.state.currencies} />
                <div className="text-center">
                    <button className="btn btn-primary" onClick={event => this.downloadAll(event)}>
                        Download all
                    </button>
                    {this.state.importEnabled ?
                        <button className="btn btn-outline-primary ml-3" onClick={event => this.importAll(event)}>
                            Import all
                    </button>
                        : null}
                </div>
            </div>
        );
    }
}
